query GetPokemons($limit: Int, $offset: Int) {
  pokemons(limit: $limit, offset: $offset) {
    count
    next
    previous
    results {
      id
      name
      image
    }
  }
}

query GetPokemon($name: String!) {
  pokemon(name: $name) {
    id
    name
    height
    weight
    abilities {
      ability {
        name
      }
    }
    types {
      type {
        name
      }
    }
    stats {
      base_stat
      stat {
        name
      }
    }
    sprites {
      front_default
      back_default
    }
  }
}
