query GetPokemons($first: Int!) {
 pokemons(first: $first) {
      id
      number
      name
      image
      types
    }
    
}

query GetPokemon($name: String){
  pokemon( name: $name){
    id
    number
    name
    weight{
      minimum
      maximum
    }
    height{
      minimum
      maximum
    }
    classification
    types
    resistant
    weaknesses
    fleeRate
    maxCP
    maxHP
    image
  }
}